Nama : Fahmi Adhiwangsa

NIM  : 1103204142


##**Import Pytorch**

##Pendhuluan Tensor

Tensor adalah struktur data dasar yang digunakan untuk menyimpan dan memanipulasi data. Tensor mirip dengan matriks atau array multidimensi, tetapi dengan fleksibilitas tambahan. Tensors dapat memiliki dimensi (rank) yang bervariasi, yang memungkinkan mereka mewakili berbagai jenis data, mulai dari skalar (0D) hingga vektor (1D), matriks (2D), hingga tensor dengan dimensi yang lebih tinggi.

Dalam PyTorch, tensor dapat digunakan untuk menyimpan data numerik, dan mereka mendukung operasi matematika yang efisien. Misalnya, tensor dapat digunakan untuk merepresentasikan input dan output dalam jaringan saraf, dan operasi tensor dapat diterapkan untuk melakukan perhitungan yang melibatkan transformasi linier, aktivasi, dan fungsi lainnya.

Tensor memberikan abstraksi yang kuat untuk bekerja dengan data numerik dalam konteks machine learning dan deep learning, dan PyTorch memiliki fungsi-fungsi bawaan yang memungkinkan manipulasi tensor dengan cepat dan efisien.





###1. Import PyTorch

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

###2. Create a random tensor with shape (6, 6).

In [11]:
tensor_random = torch.rand((6, 6))
print("Tensor Random:")
print(tensor_random)

Tensor Random:
tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593],
        [0.7204, 0.0731, 0.9699, 0.1078, 0.8829, 0.4132],
        [0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
        [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691],
        [0.7437, 0.9592, 0.3887, 0.2214, 0.3742, 0.1953],
        [0.7405, 0.2529, 0.2332, 0.9314, 0.9575, 0.5575]])


###3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 5) (hint: you may have to transpose the second tensor)

In [13]:
tensor_2 = torch.rand((1, 6))
result = torch.matmul(tensor_random, tensor_2.t())  # Mengubah tensor kedua menjadi transpose
print("\nHasil Perkalian Matriks:")
print(result, tensor_2.shape)


Hasil Perkalian Matriks:
tensor([[1.5430],
        [1.3495],
        [1.9874],
        [1.7002],
        [1.5421],
        [1.8919]]) torch.Size([1, 6])


Setiap elemen di dalam matriks tersebut adalah hasil perkalian matriks sebelumnya. Jika Anda memiliki dua matriks, katakanlah A dengan dimensi m x n dan B dengan dimensi n x p, maka hasil perkalian matriks AB akan menghasilkan matriks dengan dimensi m x p. Dalam kasus ini, matriks inputnya mungkin memiliki dimensi 1 x n, dan hasil perkalian tersebut adalah matriks 1 x p.

###4. Set the random seed to 0 and do 2 & 3 over again.

In [15]:
torch.manual_seed(0)

tensor_random = torch.rand((6, 6))
result = torch.matmul(tensor_random, tensor_2.t())
print("\nHasil Perkalian Matriks setelah Mengatur Benih Acak:")
print(result, result.shape)


Hasil Perkalian Matriks setelah Mengatur Benih Acak:
tensor([[1.3301],
        [1.5749],
        [0.9846],
        [1.3768],
        [1.0312],
        [0.9546]]) torch.Size([6, 1])


###5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [16]:
torch.cuda.manual_seed(1234)

###6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [17]:
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_gpu_1 = torch.rand((2, 3), device='cuda')
tensor_gpu_2 = torch.rand((2, 3), device='cuda')
tensor_gpu_1,tensor_gpu_2

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

Output yang Anda berikan mencakup dua tensor, dan keduanya memiliki perangkat CUDA ('cuda:0') sebagai tempat penyimpanan. Hal ini menunjukkan bahwa operasi atau inisialisasi tensor tersebut terjadi pada perangkat GPU (CUDA).



###7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [18]:
result_gpu = torch.matmul(tensor_gpu_1, tensor_gpu_2.t())  # Mengubah tensor kedua menjadi transpose
print("\nHasil Perkalian Matriks pada GPU:")
print(result_gpu, result_gpu.shape)


Hasil Perkalian Matriks pada GPU:
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


###8. Find the maximum and minimum values

In [19]:
max_value = torch.max(result_gpu)
min_value = torch.min(result_gpu)
print("\nNilai Maksimum:", max_value.item())
print("Nilai Minimum:", min_value.item())


Nilai Maksimum: 0.7667766809463501
Nilai Minimum: 0.27863210439682007


###9. Find the maximum and minimum index values.

In [20]:
argmax_index = torch.argmax(result_gpu)
argmin_index = torch.argmin(result_gpu)
print("\nIndeks Maksimum:", argmax_index.item())
print("Indeks Minimum:", argmin_index.item())


Indeks Maksimum: 1
Indeks Minimum: 0


###10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).

In [22]:
torch.manual_seed(7)
tensor_random_4d = torch.rand((1, 1, 1, 10))
tensor_flat = tensor_random_4d.view(-1)
print("\nTensor Pertama dan Bentuknya:")
print(tensor_random_4d)
print(tensor_random_4d.shape)
print("\nTensor Kedua dan Bentuknya setelah Menghapus Dimensi 1:")
print(tensor_flat)
print(tensor_flat.shape)


Tensor Pertama dan Bentuknya:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])

Tensor Kedua dan Bentuknya setelah Menghapus Dimensi 1:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
